### ISSUE TITLE
NoHTTP breaks website

### ISSUE THREAD

**Issue by damga123** [Xarib/OsuMapMatcher#1]
When using the NoHTTP add-on it doesn't seem to be possible to connect to the web part of the application. I am using firefox 86.0 and the web part works fine with NoHTTP disabled.

**Comment by Xarib** [comment]
I assume that you use this one: https://addons.mozilla.org/en-US/firefox/addon/nohttp/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search. 
From what I've read it should work. You can access the API only via HTTPS. Port 80 (HTTP) is not open. Are you sure that there isn't a problem with the add-on itself. It is still in the experimental stage.
And could you please send me the HTTP-status code you get with NoHTTP enabled.

**Comment by damga123** [comment]
The linked extension is correct, I just tried HTTPS Everywhere and Smart HTTPS. HTTPS Everywhere does not seem to block it at all while Smart HTTPS blocks it when added to blacklist. As for the HTTP-status code, In the browser console it does not give me a HTTP-status code but it does show SSL_ERROR_RX_RECORD_TOO_LONG as error code in the security tab of the connection request.

**Comment by Xarib** [comment]
I've looked into the SSL_ERROR_RX_RECORD_TOO_LONG error. I highly recommend you to read this too: https://www.thesslstore.com/blog/ssl_error_rx_record_too_long/. Your add-ons support a newer version of TLS and it seems that I have forgotten to add TLSv1.3 support. The server now supports TLSv1.2 and  TLSv1.3. This should solve your problem. I wont add any support for older TLS versions because they are insecure.
