### ISSUE TITLE
Beatmap not detected

### ISSUE THREAD

**Issue by Aksumxd** [Xarib/OsuMapMatcher#2]
![bo4uTsY 1](https://user-images.githubusercontent.com/63202855/113278179-42768c00-92ea-11eb-822b-5630a132330c.png)
The program doesn't detect me having a beatmap selected. 
![9Gj1sPT 1](https://user-images.githubusercontent.com/63202855/113278705-e7916480-92ea-11eb-98c4-7973b3ce6b35.png)

It might have something to do with me having my songs folder on a different hard drive than my osu! client. (My client is in %localappdata%\osu! and my songs are in F:\Osu maps\Songs)

**Comment by Xarib** [comment]
o/

I can't seem to reproduce your issue. I've installed osu! on an external drive and changed the BeatmapDirectory in the osu!.[USERNAME].cfg so that it points to the local Songs folder.

My Locations
- External Drive: E:\osu!\osu!.exe
- Local: S:\osu!\Songs

Can you explain to me what happens when you select a song in osu!? Something along the like: error messages or what the terminal output is. The program works the same like the osu!trainer program.

This is how it looks like when it does run properly. If you copy one of the paths at the end and paste it in the file explorer, it should open the image in photos or whatever you selected as your default.
![Capture](https://user-images.githubusercontent.com/67692366/113331582-6e146900-9320-11eb-9595-731dfd865fde.PNG)

My config file in the external drive
![image](https://user-images.githubusercontent.com/67692366/113332337-55588300-9321-11eb-9e4b-807887dd06db.png)
